/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package superdetodo;

import javax.swing.JOptionPane;
import static superdetodo.Menu.listaProductos;

/**
 *
 * @author Seba
 */
public class GestionProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGestionProductos = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelRubro = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonIngreso_Producto = new javax.swing.JButton();
        jButtonEliminar_Producto = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setClosable(true);

        jLabelGestionProductos.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabelGestionProductos.setText("Gestion de Productos");

        jLabelCodigo.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabelCodigo.setText("Codigo:");

        jLabelDescripcion.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabelDescripcion.setText("Descripcion:");

        jLabelPrecio.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabelPrecio.setText("Precio:");

        jLabelRubro.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabelRubro.setText("Rubro:");

        jLabelStock.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jLabelStock.setText("Stock:");

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMESTIBLE", "LIMPIEZA", "PERFUMERIA" }));

        jButtonIngreso_Producto.setText("Ingreso Producto");
        jButtonIngreso_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngreso_ProductoActionPerformed(evt);
            }
        });

        jButtonEliminar_Producto.setText("Eliminar Producto");
        jButtonEliminar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar_ProductoActionPerformed(evt);
            }
        });

        jButton_Editar.setText("Guardar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodigo)
                                    .addComponent(jTextFieldDescripcion)
                                    .addComponent(jTextFieldPrecio)
                                    .addComponent(jTextFieldStock)
                                    .addComponent(jComboBox1, 0, 239, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonIngreso_Producto)
                                .addGap(35, 35, 35)
                                .addComponent(jButton_Editar)
                                .addGap(41, 41, 41)
                                .addComponent(jButtonEliminar_Producto))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGestionProductos)))
                .addGap(27, 27, 27)
                .addComponent(jButtonBuscar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGestionProductos)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIngreso_Producto)
                    .addComponent(jButtonEliminar_Producto)
                    .addComponent(jButton_Editar))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonEliminar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar_ProductoActionPerformed
        // TODO add your handling code here:
       boolean eliminar = false;
        try {
            int codigo = Integer.parseInt(jTextFieldCodigo.getText().trim());
            //busco el producto por el codigo para eliminarlo
            for (Producto prod : Menu.listaProductos) {
                if (prod.getCodigo() == codigo) {
                    eliminar = true;
                    break;
                }
            }
            if (eliminar == true) {
                Menu.listaProductos.removeIf(prod -> prod.getCodigo() == codigo);
                JOptionPane.showMessageDialog(this, "Producto Eliminado");
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado");
            }
        } catch (NumberFormatException nfe) {
            //si hay datos vacios o datos incorrectos , mostrara un cartel.
            jTextFieldCodigo.setText("");
            JOptionPane.showMessageDialog(this, "Ingrese el codigo del producto que desea eliminar");
        }
        borrarCampos();  
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonEliminar_ProductoActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        
        try {
            boolean datosCorrectos=true;
            int codigo= Integer.parseInt(jTextFieldCodigo.getText().trim());
            if(codigo!=Menu.codigoBuscado){
                datosCorrectos=false;
            }
           if (jTextFieldDescripcion.getText().trim().equals("") || jTextFieldPrecio.getText().trim().equals("") || jTextFieldStock.getText().trim().equals("")) {
                datosCorrectos = false;
                JOptionPane.showMessageDialog(this, "Campos vacios, ingreselos para continuar");
            }
            
          for(Producto producto: Menu.listaProductos){             
              if(producto.getCodigo()==codigo && datosCorrectos==true){
                   String descripcion = jTextFieldDescripcion.getText().trim();
                    Double precio = Double.parseDouble(jTextFieldPrecio.getText().trim());
                    int stock = Integer.parseInt(jTextFieldStock.getText().trim());
                    String categoria = jComboBox1.getSelectedItem().toString();                   
                    producto.setDescripcion(descripcion);
                    producto.setPrecio(precio);
                    producto.setStock(stock);
               if (categoria.equalsIgnoreCase("PERFUMERIA")) {
                            producto.setRubro(Categoria.PERFUMERIA);
                        }
                        if (categoria.equalsIgnoreCase("COMESTIBLE")) {
                            producto.setRubro(Categoria.COMESTIBLE);
                        }
                        if (categoria.equalsIgnoreCase("LIMPIEZA")) {
                            producto.setRubro(Categoria.LIMPIEZA);
                        }
                        JOptionPane.showMessageDialog(this, "Cambios Guardados !");
                  }  
          }       
        } catch (NumberFormatException nfe) {
            //si hay datos vacios o datos incorrectos , mostrara un cartel.
            jTextFieldCodigo.setText("");
            JOptionPane.showMessageDialog(this, "Verifique los datos ingresados, debe ingresar un numero");
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Datos vacios, debe ingresar los datos ingresados");
        }
        borrarCampos();
 
    }//GEN-LAST:event_jButton_EditarActionPerformed
//private int codigo;
//    private String descripcion;
//    private double precio;
//    private int stock;
//    private Categoria rubro;
    private void jButtonIngreso_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngreso_ProductoActionPerformed
        // TODO add your handling code here:
 try{
        int codigo= Integer.parseInt(jTextFieldCodigo.getText().trim()) ;
        boolean productoExistente=false;
        for (Producto producto : Menu.listaProductos){
            if (producto.getCodigo()==codigo){
                jTextFieldCodigo.setText("");
                productoExistente=true;
                JOptionPane.showMessageDialog(this, "El código ya esta registrado, ingresa otro\n"
                           );
            }
        }
             String descripcion=jTextFieldDescripcion.getText().trim();
             double precio= Integer.parseInt(jTextFieldPrecio.getText().trim());
             int stock = Integer.parseInt(jTextFieldStock.getText().trim());
             String categoria= jComboBox1.getSelectedItem().toString();
             if (productoExistente == false) {
                listaProductos.add(new Producto(codigo, descripcion, precio, stock, Categoria.valueOf(categoria)));
                JOptionPane.showMessageDialog(this, "Producto Agregado");
    }//GEN-LAST:event_jButtonIngreso_ProductoActionPerformed
}catch (NumberFormatException nfe) {
            //si hay datos vacios o datos incorrectos , mostrara un cartel.
            jTextFieldCodigo.setText("");
            JOptionPane.showMessageDialog(this, "Datos incorrectos o vacios, verifique los datos ingresados");   
    }
 borrarCampos();
 }
    
    
    
    
    
    
    
    
     private void borrarCampos() {
        jTextFieldCodigo.setText("");
        jTextFieldDescripcion.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldStock.setText("");
        jComboBox1.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar_Producto;
    private javax.swing.JButton jButtonIngreso_Producto;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelGestionProductos;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelRubro;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables
}
